# Generated by Django 6.0.2 on 2026-02-23 05:21

import attendance.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', attendance.models.CustomUserManager()),
            ],
        ),
    ]
