# Generated by Django 5.0.6 on 2026-02-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('3rd Semester', '3rd Semester'), ('4th Semester', '4th Semester'), ('5th Semester', '5th Semester'), ('6th Semester', '6th Semester'), ('7th Semester', '7th Semester'), ('8th Semester', '8th Semester')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('2078', '2078'), ('2079', '2079'), ('2080', '2080'), ('2081', '2081')], max_length=4),
        ),
    ]
